### ISSUE TITLE
As a user I would like to click on a shelve on a map BACKEND

### ISSUE THREAD

**Issue by sixfourtwo** [jbb4play/leway-searchservice#5]
# Description
You get a set of coordinates, find all products inside these coordinates.

# Tasks
- [ ] New controller for searching on coordinates
- [ ] Search algorithm on coordinates (inclusive)
- [ ] Find products by ID (Use product service)
- [ ] Documentation

# Test efforts
- [ ] Test that you indeed find the correct coordinates.
